### ISSUE TITLE
Larger default list

### ISSUE THREAD

**Issue by ghost** [genesy/auto-correct#1]
Hi, would you be interested in adding more default corrections? I believe many people would get tired from constantly adding words that they would expect to be corrected by default. If they were not keen on this, they could possibly disable the default list with a setting.

Here are some useful defaults from vim-autocorrect:
https://github.com/panozzaj/vim-autocorrect/blob/master/autocorrect.dat

**Comment by genesy** [comment]
Nice list. I'll think about how to implement this without forcing it on users as real defaults. It might be better if this is just a list they can add to their list.

**Comment by jeffreypriebe** [comment]
Maybe have several "lists" in the github repo and then a config could select which "lists" to use (by name)?

A bit like adblock plus: there are ["lists"](https://easylist.to/) and one can select which ones to use.
In this case, github serving would suffice - maybe one first use, it gets copied local and then occasionally URL gets checked for updates?

**Comment by ctf0** [comment]
maybe instead of keeping a copy of lists we should implement some kind of auto-correction lib ?

**Comment by genesy** [comment]
Semi-fixed. will add functionality to read json files for ease of use (someday). for now I added useLargeList settings to use op's list
