### ISSUE TITLE
Correct words with "-" or "_"

### ISSUE THREAD

**Issue by d-koppenhagen** [genesy/auto-correct#12]
Currently correcting words like "Event-Binding" won't work with the following configuration:

```json
{
  "Eventbinding": "Event Binding" , // works
  "Event-Binding": "Event Binding", // doesn't work
  ...
}
```

I think there should be a way to get this working.

**Comment by genesy** [comment]
hmm so the issue here is that we're counting the word before the dash as a word to check. When I update to add custom trigger buttons instead of assuming all non-letter characters then that could fix it.

**Comment by d-koppenhagen** [comment]
that sounds good.

**Comment by pkaminski** [comment]
I assume this is also why `{">>": "=>"}` doesn't work?

**Comment by d-koppenhagen** [comment]
I think the part in the code that has to be changed is this one:

```ts
if (!!event.contentChanges[0].text.match(/[A-Za-z]/)) {
    return;
  }
```

This causes a return on chars like `_`, `-`, `<`, `>`, etc.

**Comment by d-koppenhagen** [comment]
@pkaminski exactly. The RegEx was just defined for common ASCII chars, but not for special characters. I provided a PR, that will expand the RegEx, so that your example will also work after merge.

**Comment by JonathanLindsey** [comment]
These also appear to be affected. Or am I doing the escape characters wrong? I want either _/ or \/ to be corrected to a checkmark.
```json
"words": {
    "_/": "✓"
    "\\/": "✓"
}
```

**Comment by d-koppenhagen** [comment]
Yes, same problem. My provided PR will fix this too 🙂

**Comment by genesy** [comment]
gonna check this out and update the extension some time today! Thank you!
