### ISSUE TITLE
Undo does not work properly

### ISSUE THREAD

**Issue by pcarbonn** [genesy/auto-correct#2]
After typing "hte " in a file, it is correctly replaced by "the", but ctrl-Z (to undo it) inserts another "the" instead of undoing the correction.

**Comment by AndrewRayCode** [comment]
I got a lot of undo entries. not immediately clear why when looking at the source.

**Comment by ctf0** [comment]
check https://marketplace.visualstudio.com/items?itemName=ctf0.auto-correct

**Comment by genesy** [comment]
Just released v1.2.0 with fix for this
