### ISSUE TITLE
unusual characters 

### ISSUE THREAD

**Issue by belclei** [genesy/auto-correct#3]
I tried use this extension to toggle "ä" by "a", but it did not work.

**Comment by jeffreypriebe** [comment]
I found a similar issue where I was trying to auto-correct my arrow functions (`+>` to `=>`) but couldn't get it to register.

Looks like [regex at L40](https://github.com/genesy/auto-correct/blob/d7e4ef1c3d1f2e5ee1e980ed2ec5db81607c0c5a/src/extension.ts#L40) may be the cause.  Not setup to do extension building, would like to get setup and fix this.

```
/(\w+)[\W]?$/g.exec('å')
--> null

/(\w+)[\W]?$/g.exec('a')
--> not null, results
```

**Comment by ctf0** [comment]
check https://marketplace.visualstudio.com/items?itemName=ctf0.auto-correct

**Comment by genesy** [comment]
could've just forked and made a pr. but okay

**Comment by ctf0** [comment]
i still can, but i thought u wont accept it because of the many changes made, check if and if okay i will send the PR

**Comment by genesy** [comment]
make the pr :)

**Comment by ctf0** [comment]
sent
